branches:
  only:
  - master
  - develop

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

language: r
sudo: required
cache: packages
warnings_are_errors: true

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - devtools
  - sessioninfo

r_github_packages:
  - r-lib/covr
  - r-lib/sessioninfo

after_success:
  - Rscript -e "covr::codecov(line_exclusions = list('R/plots.R', 'R/printing.R', 'R/utils.R'))"

notifications:
  email:
    on_success: change
    on_failure: change
